SET SERVEROUTPUT ON
CONNECT system/manager
CREATE USER appuser identified by apppassword;
GRANT CONNECT,RESOURCE,CREATE ANY DIRECTORY,DROP ANY DIRECTORY TO appuser;
ALTER USER scott GRANT CONNECT THROUGH appuser;
